name: test

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "crates/**"
      - "examples/**"
      - "bin/**"
      - "xtask/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain.toml"
      - ".github/workflows/test.yml"
      - "scripts/clippy.sh"
      - "scripts/extract_test_db.sh"
      - "scripts/rust_fmt.sh"

  pull_request:
    paths:
      - "crates/**"
      - "examples/**"
      - "bin/**"
      - "xtask/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain.toml"
      - ".github/workflows/test.yml"
      - "scripts/clippy.sh"
      - "scripts/extract_test_db.sh"
      - "scripts/rust_fmt.sh"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.90.0

jobs:
  fmt:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dojoengine/torii-dev:latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: Swatinem/rust-cache@49a0bdc70d2e1b713ca9e2869b211fcce03d3c1c # v2
      - run: scripts/rust_fmt.sh

  clippy:
    needs: [fmt]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dojoengine/torii-dev:latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: Swatinem/rust-cache@49a0bdc70d2e1b713ca9e2869b211fcce03d3c1c # v2
      - run: ./scripts/clippy.sh

  test:
    needs: [fmt, clippy]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dojoengine/torii-dev:latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: Swatinem/rust-cache@49a0bdc70d2e1b713ca9e2869b211fcce03d3c1c # v2

      - uses: software-mansion/setup-scarb@2a96b748888e3329ee44ac9ac073d930e692b3cd # v1
        with:
          scarb-version: "2.12.2"

      # This puts Katana in the path for integration tests.
      - name: Download Katana for integration tests
        run: |
          curl -L https://github.com/dojoengine/katana/releases/download/v1.7.0/katana_v1.7.0_linux_amd64.tar.gz -o katana.tar.gz;
          tar -C /usr/local/bin -xzf katana.tar.gz

      - name: Setup for integration tests
        run: |
          rustup default stable
          curl -L https://github.com/dojoengine/dojo/releases/download/v1.7.1/dojo_v1.7.1_linux_amd64.tar.gz -o dojo.tar.gz
          tar -C /usr/local/bin -xzf dojo.tar.gz
          sozo build --manifest-path examples/spawn-and-move/Scarb.toml
          sozo build --manifest-path crates/types-test/Scarb.toml

      - name: Run tests
        run: |
          bash scripts/extract_test_db.sh
          cargo nextest run --all-features --workspace --build-jobs 20
